### ISSUE TITLE
combining 2 authentication provider

### ISSUE THREAD

**Issue by bbouchen** [gouldner/cas_simple_role_test_app#1]
Hi
I'm interested of your solution combining 2 authentication provider CAS-SSO and internal authentication  as discussed in https://github.com/kakawait/cas-security-spring-boot-starter/issues/108

Could you  share with me your solution
Thanks

**Comment by gouldner** [comment]
I just added my code for Dual Authentication with CAS as primary and In Memory Auth as secondary if you visit /external_login first.

The code I just provided is also designed to be stateless because I needed that as well in my application and separating the code needed for stateless from the code needed for Dual Authentication would have taken me a lot longer to submit.  So you will need to dig into what each section is doing to pull out the parts you need.

The key to dual auth is pretty simple.
1) configure primary authentication which will be triggered by an "authenticated" request.
2) configure a login url for the secondary method. (or third.....etc)
3) When you want to login with primary method you can visit any authenticated page and you will get redirected to your primary authentication technique which will be CAS in this example.
4) When you want to visit an authenticated page using secondary login.  You first visit the secondary "login" page, in this example /external_login and then visit the page you want to see.  I have a request param "target" in case you want to send a person to the external_login and then to a specific page once they are authenticated.  This is not presented in the example but you can see the code and try for yourself to visit the target page using /external_login?target=https://......  
5) since the external_login configures authentication, now request for a authenticated page will NOT redirect you to CAS since you are already authenticated using the secondary method.

Most of the config you need is the the order http config call.

Hope that helps.

**Comment by bbouchen** [comment]
hi,
thanks you for your relpy,

i manage to build 1 scenario  as your description, but i have another one where for the secondary method i have REST API to signin

My architecture  is :
Angular application with same login page, user has choice to : 
clic on button to log with CAS server (primary method)
fill form and submit, this call an API to signin

The nice to have for me is combining CAS authentication  for  users and  Oauth 2  authentication for others

**Comment by gouldner** [comment]
You can just do a google search for adding REST security to spring boot there are plenty of posts about how that is done.

**Comment by bbouchen** [comment]
thanks
